# Generated by Django 6.0.6 on 2026-07-03 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_feedback_review_comment_feedback_review_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('screening', 'submitted_by')},
        ),
    ]
